apiVersion: autoscaling.k8s.io/v1
kind: VerticalPodAutoscaler
metadata:
  name: hudur-authentication-vpa
  namespace: hudur-platform
  labels:
    app.kubernetes.io/name: hudur-authentication-vpa
    app.kubernetes.io/part-of: hudur-platform
spec:
  targetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: hudur-authentication
  updatePolicy:
    updateMode: "Auto"
  resourcePolicy:
    containerPolicies:
    - containerName: hudur-authentication
      minAllowed:
        cpu: 100m
        memory: 128Mi
      maxAllowed:
        cpu: 2000m
        memory: 2Gi
      controlledResources: ["cpu", "memory"]
      controlledValues: RequestsAndLimits
---
apiVersion: autoscaling.k8s.io/v1
kind: VerticalPodAutoscaler
metadata:
  name: hudur-attendance-vpa
  namespace: hudur-platform
  labels:
    app.kubernetes.io/name: hudur-attendance-vpa
    app.kubernetes.io/part-of: hudur-platform
spec:
  targetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: hudur-attendance
  updatePolicy:
    updateMode: "Auto"
  resourcePolicy:
    containerPolicies:
    - containerName: hudur-attendance
      minAllowed:
        cpu: 100m
        memory: 128Mi
      maxAllowed:
        cpu: 2000m
        memory: 2Gi
      controlledResources: ["cpu", "memory"]
      controlledValues: RequestsAndLimits
---
apiVersion: autoscaling.k8s.io/v1
kind: VerticalPodAutoscaler
metadata:
  name: hudur-face-recognition-vpa
  namespace: hudur-platform
  labels:
    app.kubernetes.io/name: hudur-face-recognition-vpa
    app.kubernetes.io/part-of: hudur-platform
spec:
  targetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: hudur-face-recognition
  updatePolicy:
    updateMode: "Auto"
  resourcePolicy:
    containerPolicies:
    - containerName: hudur-face-recognition
      minAllowed:
        cpu: 200m
        memory: 256Mi
      maxAllowed:
        cpu: 4000m
        memory: 4Gi
      controlledResources: ["cpu", "memory"]
      controlledValues: RequestsAndLimits
---
apiVersion: autoscaling.k8s.io/v1
kind: VerticalPodAutoscaler
metadata:
  name: hudur-analytics-vpa
  namespace: hudur-platform
  labels:
    app.kubernetes.io/name: hudur-analytics-vpa
    app.kubernetes.io/part-of: hudur-platform
spec:
  targetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: hudur-analytics
  updatePolicy:
    updateMode: "Auto"
  resourcePolicy:
    containerPolicies:
    - containerName: hudur-analytics
      minAllowed:
        cpu: 200m
        memory: 256Mi
      maxAllowed:
        cpu: 3000m
        memory: 3Gi
      controlledResources: ["cpu", "memory"]
      controlledValues: RequestsAndLimits
---
apiVersion: autoscaling.k8s.io/v1
kind: VerticalPodAutoscaler
metadata:
  name: hudur-api-gateway-vpa
  namespace: hudur-platform
  labels:
    app.kubernetes.io/name: hudur-api-gateway-vpa
    app.kubernetes.io/part-of: hudur-platform
spec:
  targetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: hudur-api-gateway
  updatePolicy:
    updateMode: "Auto"
  resourcePolicy:
    containerPolicies:
    - containerName: hudur-api-gateway
      minAllowed:
        cpu: 100m
        memory: 128Mi
      maxAllowed:
        cpu: 1500m
        memory: 1Gi
      controlledResources: ["cpu", "memory"]
      controlledValues: RequestsAndLimits
---
apiVersion: autoscaling.k8s.io/v1
kind: VerticalPodAutoscaler
metadata:
  name: hudur-database-vpa
  namespace: hudur-platform
  labels:
    app.kubernetes.io/name: hudur-database-vpa
    app.kubernetes.io/part-of: hudur-platform
spec:
  targetRef:
    apiVersion: apps/v1
    kind: StatefulSet
    name: hudur-postgresql
  updatePolicy:
    updateMode: "Initial"
  resourcePolicy:
    containerPolicies:
    - containerName: postgresql
      minAllowed:
        cpu: 500m
        memory: 512Mi
      maxAllowed:
        cpu: 4000m
        memory: 8Gi
      controlledResources: ["cpu", "memory"]
      controlledValues: RequestsAndLimits
---
apiVersion: autoscaling.k8s.io/v1
kind: VerticalPodAutoscaler
metadata:
  name: hudur-redis-vpa
  namespace: hudur-platform
  labels:
    app.kubernetes.io/name: hudur-redis-vpa
    app.kubernetes.io/part-of: hudur-platform
spec:
  targetRef:
    apiVersion: apps/v1
    kind: StatefulSet
    name: hudur-redis
  updatePolicy:
    updateMode: "Initial"
  resourcePolicy:
    containerPolicies:
    - containerName: redis
      minAllowed:
        cpu: 100m
        memory: 128Mi
      maxAllowed:
        cpu: 1000m
        memory: 2Gi
      controlledResources: ["cpu", "memory"]
      controlledValues: RequestsAndLimits
