app = "hudur-platform-backend-fresh"
primary_region = "iad"

[build]

[env]
  PORT = "8080"

[processes]
  web = "python -m uvicorn app.main:app --host 0.0.0.0 --port 8080"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0

[[http_service.checks]]
  grace_period = "10s"
  interval = "30s"
  method = "GET"
  timeout = "5s"
  path = "/health"

[experimental]
  cmd = ["python", "-m", "uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "8080"]
