app = "attendanceplatform-api-qnzebxmq"
primary_region = "iad"

[build]
  dockerfile = "Dockerfile"

[env]
  PORT = "8080"

[processes]
<<<<<<< HEAD
  web = "python comprehensive_services.py"
||||||| 2945096
  web = "python -m uvicorn app.server:application --host 0.0.0.0 --port 8080"
=======
web = "python comprehensive_services.py"

>>>>>>> eed39a60f6b5e10c305cb9316422288e04759c18

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0

[[http_service.checks]]
  grace_period = "15s"
  interval = "30s"
  method = "GET"
  timeout = "10s"
  path = "/health"
