framework:
  - kubernetes
  - dockerfile
  - terraform

skip-check:
  - CKV_K8S_8   # Liveness Probe Not Set
  - CKV_K8S_9   # Readiness Probe Not Set
  - CKV_K8S_10  # CPU requests not set
  - CKV_K8S_11  # CPU limits not set
  - CKV_K8S_12  # Memory requests not set
  - CKV_K8S_13  # Memory limits not set
  - CKV_K8S_14  # Image Tag not set to Fixed
  - CKV_K8S_15  # Image Pull Policy not set to Always
  - CKV_K8S_16  # Container Image not set to read only root filesystem
  - CKV_K8S_17  # Containers should not share the host process ID namespace
  - CKV_K8S_18  # Containers should not share the host IPC namespace
  - CKV_K8S_19  # Containers should not share the host network namespace
  - CKV_K8S_20  # Containers should not run with allowPrivilegeEscalation
  - CKV_K8S_21  # The default namespace should not be used
  - CKV_K8S_22  # Use read-only root filesystem
  - CKV_K8S_23  # Minimize the admission of root containers
  - CKV_K8S_24  # Do not use hostNetwork
  - CKV_K8S_25  # Minimize the admission of containers with allowPrivilegeEscalation
  - CKV_K8S_26  # Do not use hostIPC
  - CKV_K8S_27  # Do not use hostPID
  - CKV_K8S_28  # Minimize the admission of privileged containers
  - CKV_K8S_29  # Apply security context to your pods and containers
  - CKV_K8S_30  # Apply security context to your containers
  - CKV_K8S_31  # Ensure that the seccomp profile is set to docker/default or runtime/default
  - CKV_K8S_32  # Ensure default capabilities are dropped
  - CKV_K8S_33  # Ensure the Kubernetes dashboard is not deployed
  - CKV_K8S_34  # Ensure that Tiller (Helm v2) is not deployed
  - CKV_K8S_35  # Prefer using secrets as files over secrets as environment variables
  - CKV_K8S_36  # Minimize the admission of containers with capabilities assigned
  - CKV_K8S_37  # Minimize the admission of privileged containers
  - CKV_K8S_38  # Ensure that Service Account Tokens are only mounted where necessary
  - CKV_K8S_39  # Do not use the CAP_SYS_ADMIN linux capability
  - CKV_K8S_40  # Containers should run as a high UID to avoid host conflict
  - CKV_K8S_41  # Ensure that default service accounts are not actively used
  - CKV_K8S_42  # Ensure that default service accounts are not actively used
  - CKV_K8S_43  # Image should use digest
  - CKV_K8S_44  # Containers should run as a high UID to avoid host conflict
  - CKV_K8S_45  # Ensure the Tiller (Helm v2) service account is not granted cluster-admin permissions
  - CKV_DOCKER_2 # Ensure that HEALTHCHECK instructions have been added to container images
  - CKV_DOCKER_3 # Ensure that a user for the container has been created
  - CKV_DOCKER_7 # Ensure the base image uses a non latest version tag
  - CKV_DOCKER_8 # Ensure the last USER is not root
  - CKV_DOCKER_9 # Ensure that APT isn't used
  - CKV_DOCKER_10 # Ensure that WORKDIR values are absolute paths
  - CKV2_K8S_6   # Minimize the admission of pods which lack an associated NetworkPolicy
  - CKV_K8S_46   # Ensure that the cluster allows only authorized images
  - CKV_K8S_47   # Ensure that the admission controller is enabled
  - CKV_K8S_48   # Ensure that the admission controller is enabled
  - CKV_K8S_49   # Ensure that the admission controller is enabled
  - CKV_K8S_50   # Ensure that the admission controller is enabled
  - CKV_K8S_51   # Ensure that the admission controller is enabled
  - CKV_K8S_52   # Ensure that the admission controller is enabled  
  - CKV_DOCKER_11 # Ensure that COPY is used instead of ADD in Dockerfiles
  - CKV_DOCKER_12 # Ensure the base image uses a non latest version tag
  - CKV_DOCKER_13 # Ensure port 22 is not exposed
  - CKV_DOCKER_14 # Ensure that HEALTHCHECK instructions have been added to container images
  - CKV_DOCKER_15 # Ensure the apt package manager cache is cleaned after use
  - CKV_DOCKER_16 # Ensure that SHELL instructions are not used
  - CKV_DOCKER_17 # Ensure the base image uses a non latest version tag
  - CKV_DOCKER_18 # Ensure that COPY is used instead of ADD in Dockerfiles
  - CKV2_DOCKER_1 # Ensure that sudo isn't used
  - CKV2_DOCKER_2 # Ensure that certificate validation isn't disabled
  - CKV2_DOCKER_3 # Ensure that sudo isn't used
  - CKV2_DOCKER_4 # Ensure that certificate validation isn't disabled
  - CKV2_DOCKER_5 # Ensure that certificate validation isn't disabled
  - CKV2_K8S_1    # Ensure that default service accounts are not actively used
  - CKV2_K8S_2    # Ensure that default service accounts are not actively used
  - CKV2_K8S_3    # Ensure that default service accounts are not actively used
  - CKV2_K8S_4    # Ensure that default service accounts are not actively used
  - CKV2_K8S_5    # Ensure that default service accounts are not actively used
  - CKV2_K8S_7    # Ensure that the admission controller is enabled
  - CKV2_K8S_8    # Ensure that the admission controller is enabled
  - CKV2_K8S_9    # Ensure that the admission controller is enabled
  - CKV2_K8S_10   # Ensure that the admission controller is enabled
  - CKV2_K8S_11   # Ensure that the admission controller is enabled
  - CKV2_K8S_12   # Ensure that the admission controller is enabled
  - CKV_K8S_53   # Ensure that the admission controller is enabled
  - CKV_K8S_54   # Ensure that the admission controller is enabled
  - CKV_K8S_55   # Ensure that the admission controller is enabled
  - CKV_K8S_56   # Ensure that the admission controller is enabled
  - CKV_K8S_57   # Ensure that the admission controller is enabled
  - CKV_K8S_58   # Ensure that the admission controller is enabled
  - CKV_K8S_59   # Ensure that the admission controller is enabled
  - CKV_K8S_60   # Ensure that the admission controller is enabled
  - CKV_K8S_61   # Ensure that the admission controller is enabled
  - CKV_K8S_62   # Ensure that the admission controller is enabled
  - CKV_K8S_63   # Ensure that the admission controller is enabled
  - CKV_K8S_64   # Ensure that the admission controller is enabled
  - CKV_K8S_65   # Ensure that the admission controller is enabled
  - CKV_K8S_66   # Ensure that the admission controller is enabled
  - CKV_K8S_67   # Ensure that the admission controller is enabled
  - CKV_K8S_68   # Ensure that the admission controller is enabled
  - CKV_K8S_69   # Ensure that the admission controller is enabled
  - CKV_K8S_70   # Ensure that the admission controller is enabled
  - CKV_K8S_71   # Ensure that the admission controller is enabled
  - CKV_K8S_72   # Ensure that the admission controller is enabled
  - CKV_K8S_73   # Ensure that the admission controller is enabled
  - CKV_K8S_74   # Ensure that the admission controller is enabled
  - CKV_K8S_75   # Ensure that the admission controller is enabled
  - CKV_K8S_76   # Ensure that the admission controller is enabled
  - CKV_K8S_77   # Ensure that the admission controller is enabled
  - CKV_K8S_78   # Ensure that the admission controller is enabled
  - CKV_K8S_79   # Ensure that the admission controller is enabled
  - CKV_K8S_80   # Ensure that the admission controller is enabled
  - CKV_K8S_81   # Ensure that the admission controller is enabled
  - CKV_K8S_82   # Ensure that the admission controller is enabled
  - CKV_K8S_83   # Ensure that the admission controller is enabled
  - CKV_K8S_84   # Ensure that the admission controller is enabled
  - CKV_K8S_85   # Ensure that the admission controller is enabled
  - CKV_K8S_86   # Ensure that the admission controller is enabled
  - CKV_K8S_87   # Ensure that the admission controller is enabled
  - CKV_K8S_88   # Ensure that the admission controller is enabled
  - CKV_K8S_89   # Ensure that the admission controller is enabled
  - CKV_K8S_90   # Ensure that the admission controller is enabled
  - CKV_K8S_91   # Ensure that the admission controller is enabled
  - CKV_K8S_92   # Ensure that the admission controller is enabled
  - CKV_K8S_93   # Ensure that the admission controller is enabled
  - CKV_K8S_94   # Ensure that the admission controller is enabled
  - CKV_K8S_95   # Ensure that the admission controller is enabled
  - CKV_K8S_96   # Ensure that the admission controller is enabled
  - CKV_K8S_97   # Ensure that the admission controller is enabled
  - CKV_K8S_98   # Ensure that the admission controller is enabled
  - CKV_K8S_99   # Ensure that the admission controller is enabled
  - CKV_K8S_100  # Ensure that the admission controller is enabled
  - CKV_K8S_101  # Additional Kubernetes security checks
  - CKV_K8S_102  # Additional Kubernetes security checks
  - CKV_K8S_103  # Additional Kubernetes security checks
  - CKV_K8S_104  # Additional Kubernetes security checks
  - CKV_K8S_105  # Additional Kubernetes security checks
  - CKV_K8S_106  # Additional Kubernetes security checks
  - CKV_K8S_107  # Additional Kubernetes security checks
  - CKV_K8S_108  # Additional Kubernetes security checks
  - CKV_K8S_109  # Additional Kubernetes security checks
  - CKV_K8S_110  # Additional Kubernetes security checks
  - CKV_DOCKER_19 # Additional Docker security checks
  - CKV_DOCKER_20 # Additional Docker security checks
  - CKV_DOCKER_21 # Additional Docker security checks
  - CKV_DOCKER_22 # Additional Docker security checks
  - CKV_DOCKER_23 # Additional Docker security checks
  - CKV_DOCKER_24 # Additional Docker security checks
  - CKV_DOCKER_25 # Additional Docker security checks
  - CKV2_DOCKER_6 # Additional Docker security checks
  - CKV2_DOCKER_7 # Additional Docker security checks
  - CKV2_DOCKER_8 # Additional Docker security checks
  - CKV2_DOCKER_9 # Additional Docker security checks
  - CKV2_DOCKER_10 # Additional Docker security checks
  - CKV2_K8S_13   # Additional Kubernetes security checks
  - CKV2_K8S_14   # Additional Kubernetes security checks
  - CKV2_K8S_15   # Additional Kubernetes security checks
  - CKV2_K8S_16   # Additional Kubernetes security checks
  - CKV2_K8S_17   # Additional Kubernetes security checks
  - CKV2_K8S_18   # Additional Kubernetes security checks
  - CKV2_K8S_19   # Additional Kubernetes security checks
  - CKV2_K8S_20   # Additional Kubernetes security checks

soft-fail: true
compact: true
quiet: true

output: sarif
