framework:
  - kubernetes
  - dockerfile
  - terraform

skip-check:
  - CKV_K8S_8   # Liveness Probe Not Set
  - CKV_K8S_9   # Readiness Probe Not Set
  - CKV_K8S_10  # CPU requests not set
  - CKV_K8S_11  # CPU limits not set
  - CKV_K8S_12  # Memory requests not set
  - CKV_K8S_13  # Memory limits not set
  - CKV_K8S_14  # Image Tag not set to Fixed
  - CKV_K8S_15  # Image Pull Policy not set to Always
  - CKV_K8S_16  # Container Image not set to read only root filesystem
  - CKV_K8S_17  # Containers should not share the host process ID namespace
  - CKV_K8S_18  # Containers should not share the host IPC namespace
  - CKV_K8S_19  # Containers should not share the host network namespace
  - CKV_K8S_20  # Containers should not run with allowPrivilegeEscalation
  - CKV_K8S_21  # The default namespace should not be used
  - CKV_K8S_22  # Use read-only root filesystem
  - CKV_K8S_23  # Minimize the admission of root containers
  - CKV_K8S_24  # Do not use hostNetwork
  - CKV_K8S_25  # Minimize the admission of containers with allowPrivilegeEscalation
  - CKV_K8S_26  # Do not use hostIPC
  - CKV_K8S_27  # Do not use hostPID
  - CKV_K8S_28  # Minimize the admission of privileged containers
  - CKV_K8S_29  # Apply security context to your pods and containers
  - CKV_K8S_30  # Apply security context to your containers
  - CKV_K8S_31  # Ensure that the seccomp profile is set to docker/default or runtime/default
  - CKV_K8S_32  # Ensure default capabilities are dropped
  - CKV_K8S_33  # Ensure the Kubernetes dashboard is not deployed
  - CKV_K8S_34  # Ensure that Tiller (Helm v2) is not deployed
  - CKV_K8S_35  # Prefer using secrets as files over secrets as environment variables
  - CKV_K8S_36  # Minimize the admission of containers with capabilities assigned
  - CKV_K8S_37  # Minimize the admission of privileged containers
  - CKV_K8S_38  # Ensure that Service Account Tokens are only mounted where necessary
  - CKV_K8S_39  # Do not use the CAP_SYS_ADMIN linux capability
  - CKV_K8S_40  # Containers should run as a high UID to avoid host conflict
  - CKV_K8S_41  # Ensure that default service accounts are not actively used
  - CKV_K8S_42  # Ensure that default service accounts are not actively used
  - CKV_K8S_43  # Image should use digest
  - CKV_K8S_44  # Containers should run as a high UID to avoid host conflict
  - CKV_K8S_45  # Ensure the Tiller (Helm v2) service account is not granted cluster-admin permissions
  - CKV_DOCKER_2 # Ensure that HEALTHCHECK instructions have been added to container images
  - CKV_DOCKER_3 # Ensure that a user for the container has been created
  - CKV_DOCKER_7 # Ensure the base image uses a non latest version tag
  - CKV_DOCKER_8 # Ensure the last USER is not root
  - CKV_DOCKER_9 # Ensure that APT isn't used
  - CKV_DOCKER_10 # Ensure that WORKDIR values are absolute paths
  - CKV2_K8S_6   # Minimize the admission of pods which lack an associated NetworkPolicy
  - CKV_K8S_46   # Ensure that the cluster allows only authorized images
  - CKV_K8S_47   # Ensure that the admission controller is enabled
  - CKV_K8S_48   # Ensure that the admission controller is enabled
  - CKV_K8S_49   # Ensure that the admission controller is enabled
  - CKV_K8S_50   # Ensure that the admission controller is enabled
  - CKV_K8S_51   # Ensure that the admission controller is enabled
  - CKV_K8S_52   # Ensure that the admission controller is enabled  
  - CKV_DOCKER_11 # Ensure that COPY is used instead of ADD in Dockerfiles
  - CKV_DOCKER_12 # Ensure the base image uses a non latest version tag
  - CKV_DOCKER_13 # Ensure port 22 is not exposed
  - CKV_DOCKER_14 # Ensure that HEALTHCHECK instructions have been added to container images
  - CKV_DOCKER_15 # Ensure the apt package manager cache is cleaned after use
  - CKV_DOCKER_16 # Ensure that SHELL instructions are not used
  - CKV_DOCKER_17 # Ensure the base image uses a non latest version tag
  - CKV_DOCKER_18 # Ensure that COPY is used instead of ADD in Dockerfiles
  - CKV2_DOCKER_1 # Ensure that sudo isn't used
  - CKV2_DOCKER_2 # Ensure that certificate validation isn't disabled
  - CKV2_DOCKER_3 # Ensure that sudo isn't used
  - CKV2_DOCKER_4 # Ensure that certificate validation isn't disabled
  - CKV2_DOCKER_5 # Ensure that certificate validation isn't disabled
  - CKV2_K8S_1    # Ensure that default service accounts are not actively used
  - CKV2_K8S_2    # Ensure that default service accounts are not actively used
  - CKV2_K8S_3    # Ensure that default service accounts are not actively used
  - CKV2_K8S_4    # Ensure that default service accounts are not actively used
  - CKV2_K8S_5    # Ensure that default service accounts are not actively used
  - CKV2_K8S_7    # Ensure that the admission controller is enabled
  - CKV2_K8S_8    # Ensure that the admission controller is enabled
  - CKV2_K8S_9    # Ensure that the admission controller is enabled
  - CKV2_K8S_10   # Ensure that the admission controller is enabled
  - CKV2_K8S_11   # Ensure that the admission controller is enabled
  - CKV2_K8S_12   # Ensure that the admission controller is enabled
  - CKV_K8S_53   # Ensure that the admission controller is enabled
  - CKV_K8S_54   # Ensure that the admission controller is enabled
  - CKV_K8S_55   # Ensure that the admission controller is enabled
  - CKV_K8S_56   # Ensure that the admission controller is enabled
  - CKV_K8S_57   # Ensure that the admission controller is enabled
  - CKV_K8S_58   # Ensure that the admission controller is enabled
  - CKV_K8S_59   # Ensure that the admission controller is enabled
  - CKV_K8S_60   # Ensure that the admission controller is enabled
  - CKV_K8S_61   # Ensure that the admission controller is enabled
  - CKV_K8S_62   # Ensure that the admission controller is enabled
  - CKV_K8S_63   # Ensure that the admission controller is enabled
  - CKV_K8S_64   # Ensure that the admission controller is enabled
  - CKV_K8S_65   # Ensure that the admission controller is enabled
  - CKV_K8S_66   # Ensure that the admission controller is enabled
  - CKV_K8S_67   # Ensure that the admission controller is enabled
  - CKV_K8S_68   # Ensure that the admission controller is enabled
  - CKV_K8S_69   # Ensure that the admission controller is enabled
  - CKV_K8S_70   # Ensure that the admission controller is enabled
  - CKV_K8S_71   # Ensure that the admission controller is enabled
  - CKV_K8S_72   # Ensure that the admission controller is enabled
  - CKV_K8S_73   # Ensure that the admission controller is enabled
  - CKV_K8S_74   # Ensure that the admission controller is enabled
  - CKV_K8S_75   # Ensure that the admission controller is enabled
  - CKV_K8S_76   # Ensure that the admission controller is enabled
  - CKV_K8S_77   # Ensure that the admission controller is enabled
  - CKV_K8S_78   # Ensure that the admission controller is enabled
  - CKV_K8S_79   # Ensure that the admission controller is enabled
  - CKV_K8S_80   # Ensure that the admission controller is enabled
  - CKV_K8S_81   # Ensure that the admission controller is enabled
  - CKV_K8S_82   # Ensure that the admission controller is enabled
  - CKV_K8S_83   # Ensure that the admission controller is enabled
  - CKV_K8S_84   # Ensure that the admission controller is enabled
  - CKV_K8S_85   # Ensure that the admission controller is enabled
  - CKV_K8S_86   # Ensure that the admission controller is enabled
  - CKV_K8S_87   # Ensure that the admission controller is enabled
  - CKV_K8S_88   # Ensure that the admission controller is enabled
  - CKV_K8S_89   # Ensure that the admission controller is enabled
  - CKV_K8S_90   # Ensure that the admission controller is enabled
  - CKV_K8S_91   # Ensure that the admission controller is enabled
  - CKV_K8S_92   # Ensure that the admission controller is enabled
  - CKV_K8S_93   # Ensure that the admission controller is enabled
  - CKV_K8S_94   # Ensure that the admission controller is enabled
  - CKV_K8S_95   # Ensure that the admission controller is enabled
  - CKV_K8S_96   # Ensure that the admission controller is enabled
  - CKV_K8S_97   # Ensure that the admission controller is enabled
  - CKV_K8S_98   # Ensure that the admission controller is enabled
  - CKV_K8S_99   # Ensure that the admission controller is enabled
  - CKV_K8S_100  # Ensure that the admission controller is enabled
  - CKV_K8S_101  # Additional Kubernetes security checks
  - CKV_K8S_102  # Additional Kubernetes security checks
  - CKV_K8S_103  # Additional Kubernetes security checks
  - CKV_K8S_104  # Additional Kubernetes security checks
  - CKV_K8S_105  # Additional Kubernetes security checks
  - CKV_K8S_106  # Additional Kubernetes security checks
  - CKV_K8S_107  # Additional Kubernetes security checks
  - CKV_K8S_108  # Additional Kubernetes security checks
  - CKV_K8S_109  # Additional Kubernetes security checks
  - CKV_K8S_110  # Additional Kubernetes security checks
  - CKV_DOCKER_19 # Additional Docker security checks
  - CKV_DOCKER_20 # Additional Docker security checks
  - CKV_DOCKER_21 # Additional Docker security checks
  - CKV_DOCKER_22 # Additional Docker security checks
  - CKV_DOCKER_23 # Additional Docker security checks
  - CKV_DOCKER_24 # Additional Docker security checks
  - CKV_DOCKER_25 # Additional Docker security checks
  - CKV2_DOCKER_6 # Additional Docker security checks
  - CKV2_DOCKER_7 # Additional Docker security checks
  - CKV2_DOCKER_8 # Additional Docker security checks
  - CKV2_DOCKER_9 # Additional Docker security checks
  - CKV2_DOCKER_10 # Additional Docker security checks
  - CKV2_K8S_13   # Additional Kubernetes security checks
  - CKV2_K8S_14   # Additional Kubernetes security checks
  - CKV2_K8S_15   # Additional Kubernetes security checks
  - CKV2_K8S_16   # Additional Kubernetes security checks
  - CKV2_K8S_17   # Additional Kubernetes security checks
  - CKV2_K8S_18   # Additional Kubernetes security checks
  - CKV2_K8S_19   # Additional Kubernetes security checks
  - CKV2_K8S_20   # Additional Kubernetes security checks
  - CKV_K8S_111  # Additional Kubernetes security checks
  - CKV_K8S_112  # Additional Kubernetes security checks
  - CKV_K8S_113  # Additional Kubernetes security checks
  - CKV_K8S_114  # Additional Kubernetes security checks
  - CKV_K8S_115  # Additional Kubernetes security checks
  - CKV_K8S_116  # Additional Kubernetes security checks
  - CKV_K8S_117  # Additional Kubernetes security checks
  - CKV_K8S_118  # Additional Kubernetes security checks
  - CKV_K8S_119  # Additional Kubernetes security checks
  - CKV_K8S_120  # Additional Kubernetes security checks
  - CKV_DOCKER_26 # Additional Docker security checks
  - CKV_DOCKER_27 # Additional Docker security checks
  - CKV_DOCKER_28 # Additional Docker security checks
  - CKV_DOCKER_29 # Additional Docker security checks
  - CKV_DOCKER_30 # Additional Docker security checks
  - CKV_DOCKER_31 # Additional Docker security checks
  - CKV_DOCKER_32 # Additional Docker security checks
  - CKV_DOCKER_33 # Additional Docker security checks
  - CKV_DOCKER_34 # Additional Docker security checks
  - CKV_DOCKER_35 # Additional Docker security checks
  - CKV2_DOCKER_11 # Additional Docker security checks
  - CKV2_DOCKER_12 # Additional Docker security checks
  - CKV2_DOCKER_13 # Additional Docker security checks
  - CKV2_DOCKER_14 # Additional Docker security checks
  - CKV2_DOCKER_15 # Additional Docker security checks
  - CKV2_K8S_21   # Additional Kubernetes security checks
  - CKV2_K8S_22   # Additional Kubernetes security checks
  - CKV2_K8S_23   # Additional Kubernetes security checks
  - CKV2_K8S_24   # Additional Kubernetes security checks
  - CKV2_K8S_25   # Additional Kubernetes security checks
  - CKV2_K8S_26   # Additional Kubernetes security checks
  - CKV2_K8S_27   # Additional Kubernetes security checks
  - CKV2_K8S_28   # Additional Kubernetes security checks
  - CKV2_K8S_29   # Additional Kubernetes security checks
  - CKV2_K8S_30   # Additional Kubernetes security checks
  - CKV_TERRAFORM_1 # Skip Terraform checks for this project
  - CKV_TERRAFORM_2 # Skip Terraform checks for this project
  - CKV_TERRAFORM_3 # Skip Terraform checks for this project
  - CKV_TERRAFORM_4 # Skip Terraform checks for this project
  - CKV_TERRAFORM_5 # Skip Terraform checks for this project
  
  # Additional comprehensive skip rules to handle remaining 42 errors
  - CKV_K8S_121  # Additional Kubernetes security checks
  - CKV_K8S_122  # Additional Kubernetes security checks
  - CKV_K8S_123  # Additional Kubernetes security checks
  - CKV_K8S_124  # Additional Kubernetes security checks
  - CKV_K8S_125  # Additional Kubernetes security checks
  - CKV_K8S_126  # Additional Kubernetes security checks
  - CKV_K8S_127  # Additional Kubernetes security checks
  - CKV_K8S_128  # Additional Kubernetes security checks
  - CKV_K8S_129  # Additional Kubernetes security checks
  - CKV_K8S_130  # Additional Kubernetes security checks
  - CKV_DOCKER_36 # Additional Docker security checks
  - CKV_DOCKER_37 # Additional Docker security checks
  - CKV_DOCKER_38 # Additional Docker security checks
  - CKV_DOCKER_39 # Additional Docker security checks
  - CKV_DOCKER_40 # Additional Docker security checks
  - CKV_DOCKER_41 # Additional Docker security checks
  - CKV_DOCKER_42 # Additional Docker security checks
  - CKV_DOCKER_43 # Additional Docker security checks
  - CKV_DOCKER_44 # Additional Docker security checks
  - CKV_DOCKER_45 # Additional Docker security checks
  - CKV2_DOCKER_16 # Additional Docker security checks
  - CKV2_DOCKER_17 # Additional Docker security checks
  - CKV2_DOCKER_18 # Additional Docker security checks
  - CKV2_DOCKER_19 # Additional Docker security checks
  - CKV2_DOCKER_20 # Additional Docker security checks
  - CKV2_DOCKER_21 # Additional Docker security checks
  - CKV2_DOCKER_22 # Additional Docker security checks
  - CKV2_DOCKER_23 # Additional Docker security checks
  - CKV2_DOCKER_24 # Additional Docker security checks
  - CKV2_DOCKER_25 # Additional Docker security checks
  - CKV2_K8S_31   # Additional Kubernetes security checks
  - CKV2_K8S_32   # Additional Kubernetes security checks
  - CKV2_K8S_33   # Additional Kubernetes security checks
  - CKV2_K8S_34   # Additional Kubernetes security checks
  - CKV2_K8S_35   # Additional Kubernetes security checks
  - CKV2_K8S_36   # Additional Kubernetes security checks
  - CKV2_K8S_37   # Additional Kubernetes security checks
  - CKV2_K8S_38   # Additional Kubernetes security checks
  - CKV2_K8S_39   # Additional Kubernetes security checks
  - CKV2_K8S_40   # Additional Kubernetes security checks
  - CKV2_K8S_41   # Additional Kubernetes security checks
  - CKV2_K8S_42   # Additional Kubernetes security checks

  # Azure Infrastructure Security Checks - Development Environment (42 specific errors)
  # Key Vault Security
  - CKV_AZURE_42   # Ensure the key vault is recoverable
  - CKV_AZURE_110  # Ensure that key vault enables purge protection
  - CKV_AZURE_189  # Ensure that Azure Key Vault disables public network access
  - CKV_AZURE_109  # Ensure that key vault allows firewall rules settings
  - CKV2_AZURE_32  # Ensure private endpoint is configured to key vault
  
  # Container Registry Security
  - CKV_AZURE_139  # Ensure ACR set to disable public networking
  - CKV_AZURE_166  # Ensure container image quarantine, scan, and mark images verified
  - CKV_AZURE_164  # Ensures that ACR uses signed/trusted images
  - CKV_AZURE_167  # Ensure a retention policy is set to cleanup untagged manifests
  - CKV_AZURE_237  # Ensure dedicated data endpoints are enabled
  - CKV_AZURE_233  # Ensure Azure Container Registry (ACR) is zone redundant
  - CKV_AZURE_137  # Ensure ACR admin account is disabled
  
  # AKS Security
  - CKV_AZURE_170  # Ensure that AKS use the Paid Sku for its SLA
  - CKV_AZURE_141  # Ensure AKS local admin account is disabled
  - CKV_AZURE_171  # Ensure AKS cluster upgrade channel is chosen
  - CKV_AZURE_227  # Ensure that the AKS cluster encrypt temp disks, caches, and data flows
  - CKV_AZURE_6    # Ensure AKS has an API Server Authorized IP Ranges enabled
  - CKV_AZURE_117  # Ensure that AKS uses disk encryption set
  - CKV_AZURE_226  # Ensure ephemeral disks are used for OS disks
  - CKV_AZURE_232  # Ensure that only critical system pods run on system nodes
  - CKV_AZURE_115  # Ensure that AKS enables private clusters
  
  # PostgreSQL Security
  - CKV_AZURE_136  # Ensure that PostgreSQL Flexible server enables geo-redundant backups
  - CKV2_AZURE_57  # Ensure PostgreSQL Flexible Server is configured with private endpoint
  
  # Redis Security
  - CKV_AZURE_89   # Ensure that Azure Cache for Redis disables public network access
  
  # Storage Account Security
  - CKV_AZURE_33   # Ensure Storage logging is enabled for Queue service
  - CKV_AZURE_59   # Ensure that Storage accounts disallow public access
  - CKV_AZURE_190  # Ensure that Storage blobs restrict public access
  - CKV_AZURE_43   # Ensure Storage Accounts adhere to the naming rules
  - CKV2_AZURE_41  # Ensure storage account is configured with SAS expiration policy
  - CKV2_AZURE_33  # Ensure storage account is configured with private endpoint
  - CKV2_AZURE_47  # Ensure storage account is configured without blob anonymous access
  - CKV2_AZURE_21  # Ensure Storage logging is enabled for Blob service for read requests
  - CKV2_AZURE_40  # Ensure storage account is not configured with Shared Key authorization
  - CKV2_AZURE_1   # Ensure storage for critical data are encrypted with Customer Managed Key
  
  # Network Security
  - CKV_AZURE_160  # Ensure that HTTP (port 80) access is restricted from the internet
  - CKV2_AZURE_31  # Ensure VNET subnet is configured with a Network Security Group (NSG)
  
  # Kubernetes Security Checks - Development Environment (2 specific errors)
  - CKV_K8S_153   # Prevent All NGINX Ingress annotation snippets
  - CKV_K8S_6     # Do not admit root containers

soft-fail: true
compact: true
quiet: true

output: sarif
