global:
  smtp_smarthost: 'localhost:587'
  smtp_from: 'alerts@hudur.sa'
  smtp_auth_username: 'alerts@hudur.sa'
  smtp_auth_password: '${SMTP_PASSWORD}'

route:
  group_by: ['alertname', 'cluster', 'service']
  group_wait: 10s
  group_interval: 10s
  repeat_interval: 1h
  receiver: 'web.hook'
  routes:
    - match:
        severity: critical
      receiver: 'critical-alerts'
      group_wait: 5s
      repeat_interval: 5m
    - match:
        severity: warning
      receiver: 'warning-alerts'
      group_wait: 30s
      repeat_interval: 30m
    - match:
        alertname: 'HighErrorRate'
      receiver: 'error-alerts'
      group_wait: 10s
      repeat_interval: 10m
    - match:
        alertname: 'ServiceDown'
      receiver: 'service-down-alerts'
      group_wait: 5s
      repeat_interval: 2m

receivers:
  - name: 'web.hook'
    webhook_configs:
      - url: 'http://monitoring-api:8093/api/monitoring/alerts/webhook'
        send_resolved: true

  - name: 'critical-alerts'
    email_configs:
      - to: 'admin@hudur.sa'
        subject: '🚨 CRITICAL: {{ .GroupLabels.alertname }} - {{ .GroupLabels.service }}'
        body: |
          Alert: {{ .GroupLabels.alertname }}
          Service: {{ .GroupLabels.service }}
          Severity: {{ .CommonLabels.severity }}
          
          {{ range .Alerts }}
          Description: {{ .Annotations.description }}
          Summary: {{ .Annotations.summary }}
          Started: {{ .StartsAt }}
          {{ end }}
          
          Dashboard: https://grafana.hudur.sa/d/system-overview
    slack_configs:
      - api_url: '${SLACK_WEBHOOK_URL}'
        channel: '#alerts-critical'
        title: '🚨 Critical Alert: {{ .GroupLabels.alertname }}'
        text: |
          Service: {{ .GroupLabels.service }}
          {{ range .Alerts }}{{ .Annotations.description }}{{ end }}
    webhook_configs:
      - url: 'http://notifications-api:8086/api/notifications/alerts/critical'
        send_resolved: true

  - name: 'warning-alerts'
    email_configs:
      - to: 'ops@hudur.sa'
        subject: '⚠️ WARNING: {{ .GroupLabels.alertname }} - {{ .GroupLabels.service }}'
        body: |
          Alert: {{ .GroupLabels.alertname }}
          Service: {{ .GroupLabels.service }}
          Severity: {{ .CommonLabels.severity }}
          
          {{ range .Alerts }}
          Description: {{ .Annotations.description }}
          Summary: {{ .Annotations.summary }}
          Started: {{ .StartsAt }}
          {{ end }}
    slack_configs:
      - api_url: '${SLACK_WEBHOOK_URL}'
        channel: '#alerts-warning'
        title: '⚠️ Warning: {{ .GroupLabels.alertname }}'
        text: |
          Service: {{ .GroupLabels.service }}
          {{ range .Alerts }}{{ .Annotations.description }}{{ end }}

  - name: 'error-alerts'
    email_configs:
      - to: 'dev@hudur.sa'
        subject: '🔥 HIGH ERROR RATE: {{ .GroupLabels.service }}'
        body: |
          Service: {{ .GroupLabels.service }}
          Error Rate Alert Triggered
          
          {{ range .Alerts }}
          Description: {{ .Annotations.description }}
          Current Value: {{ .Annotations.value }}
          Threshold: {{ .Annotations.threshold }}
          {{ end }}
    webhook_configs:
      - url: 'http://notifications-api:8086/api/notifications/alerts/errors'
        send_resolved: true

  - name: 'service-down-alerts'
    email_configs:
      - to: 'admin@hudur.sa,ops@hudur.sa'
        subject: '💥 SERVICE DOWN: {{ .GroupLabels.service }}'
        body: |
          URGENT: Service {{ .GroupLabels.service }} is DOWN
          
          {{ range .Alerts }}
          Description: {{ .Annotations.description }}
          Started: {{ .StartsAt }}
          {{ end }}
          
          Immediate action required!
    slack_configs:
      - api_url: '${SLACK_WEBHOOK_URL}'
        channel: '#alerts-critical'
        title: '💥 SERVICE DOWN: {{ .GroupLabels.service }}'
        text: |
          @channel URGENT: Service is completely down!
          {{ range .Alerts }}{{ .Annotations.description }}{{ end }}
    webhook_configs:
      - url: 'http://notifications-api:8086/api/notifications/alerts/service-down'
        send_resolved: true

inhibit_rules:
  - source_match:
      severity: 'critical'
    target_match:
      severity: 'warning'
    equal: ['alertname', 'service']

  - source_match:
      alertname: 'ServiceDown'
    target_match_re:
      alertname: '.*'
    equal: ['service']
