global:
  scrape_interval: 15s
  evaluation_interval: 15s
  external_labels:
    cluster: 'hudur-production'
    environment: 'production'

rule_files:
  - "alert_rules.yml"
  - "business_rules.yml"
  - "sla_rules.yml"

alerting:
  alertmanagers:
    - static_configs:
        - targets:
          - alertmanager:9093
      path_prefix: /alertmanager
      scheme: http

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']
    scrape_interval: 15s

  # Core Microservices
  - job_name: 'attendance-api'
    static_configs:
      - targets: ['attendance-service:80']
    metrics_path: '/metrics'
    scrape_interval: 30s
    scrape_timeout: 10s

  - job_name: 'authentication-api'
    static_configs:
      - targets: ['authentication-service:80']
    metrics_path: '/metrics'
    scrape_interval: 30s
    scrape_timeout: 10s

  - job_name: 'face-recognition-api'
    static_configs:
      - targets: ['face-recognition-service:80']
    metrics_path: '/metrics'
    scrape_interval: 30s
    scrape_timeout: 10s

  - job_name: 'leave-management-api'
    static_configs:
      - targets: ['leave-management-service:80']
    metrics_path: '/metrics'
    scrape_interval: 30s
    scrape_timeout: 10s

  - job_name: 'user-management-api'
    static_configs:
      - targets: ['user-management-service:80']
    metrics_path: '/metrics'
    scrape_interval: 30s
    scrape_timeout: 10s

  - job_name: 'tenant-management-api'
    static_configs:
      - targets: ['tenant-management-service:80']
    metrics_path: '/metrics'
    scrape_interval: 30s
    scrape_timeout: 10s

  - job_name: 'notifications-api'
    static_configs:
      - targets: ['notifications-service:80']
    metrics_path: '/metrics'
    scrape_interval: 30s
    scrape_timeout: 10s

  - job_name: 'webhooks-api'
    static_configs:
      - targets: ['webhooks-service:80']
    metrics_path: '/metrics'
    scrape_interval: 30s
    scrape_timeout: 10s

  # Advanced Services
  - job_name: 'analytics-api'
    static_configs:
      - targets: ['analytics-service:80']
    metrics_path: '/metrics'
    scrape_interval: 30s
    scrape_timeout: 10s

  - job_name: 'workflow-engine-api'
    static_configs:
      - targets: ['workflow-engine-service:80']
    metrics_path: '/metrics'
    scrape_interval: 30s
    scrape_timeout: 10s

  - job_name: 'integrations-api'
    static_configs:
      - targets: ['integrations-service:80']
    metrics_path: '/metrics'
    scrape_interval: 30s
    scrape_timeout: 10s

  - job_name: 'collaboration-api'
    static_configs:
      - targets: ['collaboration-service:80']
    metrics_path: '/metrics'
    scrape_interval: 30s
    scrape_timeout: 10s

  - job_name: 'voice-recognition-api'
    static_configs:
      - targets: ['voice-recognition-service:80']
    metrics_path: '/metrics'
    scrape_interval: 30s
    scrape_timeout: 10s

  - job_name: 'monitoring-api'
    static_configs:
      - targets: ['monitoring-service:80']
    metrics_path: '/metrics'
    scrape_interval: 15s
    scrape_timeout: 10s

  - job_name: 'compliance-api'
    static_configs:
      - targets: ['compliance-service:80']
    metrics_path: '/metrics'
    scrape_interval: 30s
    scrape_timeout: 10s

  # Infrastructure Components
  - job_name: 'api-gateway'
    static_configs:
      - targets: ['api-gateway:80']
    metrics_path: '/metrics'
    scrape_interval: 15s
    scrape_timeout: 10s

  - job_name: 'redis'
    static_configs:
      - targets: ['redis:6379']
    metrics_path: '/metrics'
    scrape_interval: 30s

  - job_name: 'rabbitmq'
    static_configs:
      - targets: ['rabbitmq:15692']

  - job_name: 'sql-server'
    static_configs:
      - targets: ['sql-server:1433']
    metrics_path: '/metrics'
    scrape_interval: 60s

  - job_name: 'frontend'
    static_configs:
      - targets: ['frontend:80']
    metrics_path: '/metrics'
    scrape_interval: 30s

  - job_name: 'node-exporter'
    static_configs:
      - targets: ['node-exporter:9100']

  # Business Metrics Collection
  - job_name: 'business-metrics'
    static_configs:
      - targets: ['monitoring-service:80']
    metrics_path: '/api/monitoring/metrics'
    scrape_interval: 60s
    scrape_timeout: 30s
