apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: hudur-attendance-platform
  namespace: argocd
  labels:
    app.kubernetes.io/name: hudur-attendance-platform
    app.kubernetes.io/part-of: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/Alsairy/AttendancePro
    targetRevision: HEAD
    path: helm/hudur
    helm:
      valueFiles:
        - values.yaml
      parameters:
        - name: global.environment
          value: production
        - name: global.domain
          value: hudur.sa
        - name: global.imageRegistry
          value: hudurprodacr.azurecr.io
  destination:
    server: https://kubernetes.default.svc
    namespace: hudur-platform
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: false
    syncOptions:
      - CreateNamespace=true
      - PrunePropagationPolicy=foreground
      - PruneLast=true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
  revisionHistoryLimit: 10
  ignoreDifferences:
    - group: apps
      kind: Deployment
      jsonPointers:
        - /spec/replicas
    - group: ""
      kind: Service
      jsonPointers:
        - /spec/clusterIP
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: hudur-monitoring-stack
  namespace: argocd
  labels:
    app.kubernetes.io/name: hudur-monitoring-stack
    app.kubernetes.io/part-of: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/Alsairy/AttendancePro
    targetRevision: HEAD
    path: k8s/monitoring
  destination:
    server: https://kubernetes.default.svc
    namespace: hudur-monitoring
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: false
    syncOptions:
      - CreateNamespace=true
      - PrunePropagationPolicy=foreground
      - PruneLast=true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
  revisionHistoryLimit: 10
---
apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: hudur-platform
  namespace: argocd
  labels:
    app.kubernetes.io/name: hudur-platform-project
    app.kubernetes.io/part-of: argocd
spec:
  description: Hudur AttendancePro Platform Project
  sourceRepos:
    - https://github.com/Alsairy/AttendancePro
    - https://charts.bitnami.com/bitnami
    - https://kubernetes.github.io/ingress-nginx
    - https://charts.jetstack.io
    - https://prometheus-community.github.io/helm-charts
    - https://grafana.github.io/helm-charts
  destinations:
    - namespace: hudur-platform
      server: https://kubernetes.default.svc
    - namespace: hudur-monitoring
      server: https://kubernetes.default.svc
    - namespace: hudur-staging
      server: https://kubernetes.default.svc
  clusterResourceWhitelist:
    - group: ""
      kind: Namespace
    - group: ""
      kind: PersistentVolume
    - group: storage.k8s.io
      kind: StorageClass
    - group: networking.k8s.io
      kind: IngressClass
    - group: rbac.authorization.k8s.io
      kind: ClusterRole
    - group: rbac.authorization.k8s.io
      kind: ClusterRoleBinding
    - group: apiextensions.k8s.io
      kind: CustomResourceDefinition
  namespaceResourceWhitelist:
    - group: ""
      kind: "*"
    - group: apps
      kind: "*"
    - group: extensions
      kind: "*"
    - group: networking.k8s.io
      kind: "*"
    - group: autoscaling
      kind: "*"
    - group: policy
      kind: "*"
    - group: rbac.authorization.k8s.io
      kind: "*"
    - group: monitoring.coreos.com
      kind: "*"
    - group: cert-manager.io
      kind: "*"
  roles:
    - name: admin
      description: Admin access to Hudur Platform
      policies:
        - p, proj:hudur-platform:admin, applications, *, hudur-platform/*, allow
        - p, proj:hudur-platform:admin, repositories, *, *, allow
        - p, proj:hudur-platform:admin, clusters, *, *, allow
      groups:
        - hudur:platform-admins
    - name: developer
      description: Developer access to Hudur Platform
      policies:
        - p, proj:hudur-platform:developer, applications, get, hudur-platform/*, allow
        - p, proj:hudur-platform:developer, applications, sync, hudur-platform/*, allow
        - p, proj:hudur-platform:developer, repositories, get, *, allow
      groups:
        - hudur:developers
