apiVersion: v1
kind: Secret
metadata:
  name: hudur-repo-secret
  namespace: argocd
  labels:
    argocd.argoproj.io/secret-type: repository
type: Opaque
stringData:
  type: git
  url: https://github.com/Alsairy/AttendancePro
  password: ""
  username: ""
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-repositories
  namespace: argocd
  labels:
    app.kubernetes.io/name: argocd-repositories
    app.kubernetes.io/part-of: argocd
data:
  repositories: |
    - url: https://github.com/Alsairy/AttendancePro
      name: hudur-platform
      type: git
    - url: https://charts.bitnami.com/bitnami
      name: bitnami
      type: helm
    - url: https://kubernetes.github.io/ingress-nginx
      name: ingress-nginx
      type: helm
    - url: https://charts.jetstack.io
      name: jetstack
      type: helm
    - url: https://prometheus-community.github.io/helm-charts
      name: prometheus-community
      type: helm
    - url: https://grafana.github.io/helm-charts
      name: grafana
      type: helm
