apiVersion: apps/v1
kind: Deployment
metadata:
  name: leave-management-service
  namespace: attendancepro
  labels:
    app: leave-management-service
    tier: backend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: leave-management-service
  template:
    metadata:
      labels:
        app: leave-management-service
        tier: backend
    spec:
      containers:
      - name: leave-management-service
        image: attendancepro/leave-management-service:latest
        ports:
        - containerPort: 80
        envFrom:
        - configMapRef:
            name: attendancepro-config
        env:
        - name: ASPNETCORE_ENVIRONMENT
          value: "Production"
        - name: ASPNETCORE_URLS
          value: "http://+:80"
        resources:
          requests:
            memory: "256Mi"
            cpu: "100m"
          limits:
            memory: "512Mi"
            cpu: "500m"
        livenessProbe:
          httpGet:
            path: /health
            port: 80
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /health
            port: 80
          initialDelaySeconds: 5
          periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: leave-management-service
  namespace: attendancepro
spec:
  selector:
    app: leave-management-service
  ports:
  - port: 80
    targetPort: 80
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: notifications-service
  namespace: attendancepro
  labels:
    app: notifications-service
    tier: backend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: notifications-service
  template:
    metadata:
      labels:
        app: notifications-service
        tier: backend
    spec:
      containers:
      - name: notifications-service
        image: attendancepro/notifications-service:latest
        ports:
        - containerPort: 80
        envFrom:
        - configMapRef:
            name: attendancepro-config
        env:
        - name: ASPNETCORE_ENVIRONMENT
          value: "Production"
        - name: ASPNETCORE_URLS
          value: "http://+:80"
        resources:
          requests:
            memory: "256Mi"
            cpu: "100m"
          limits:
            memory: "512Mi"
            cpu: "500m"
        livenessProbe:
          httpGet:
            path: /health
            port: 80
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /health
            port: 80
          initialDelaySeconds: 5
          periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: notifications-service
  namespace: attendancepro
spec:
  selector:
    app: notifications-service
  ports:
  - port: 80
    targetPort: 80
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: webhooks-service
  namespace: attendancepro
  labels:
    app: webhooks-service
    tier: backend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: webhooks-service
  template:
    metadata:
      labels:
        app: webhooks-service
        tier: backend
    spec:
      containers:
      - name: webhooks-service
        image: attendancepro/webhooks-service:latest
        ports:
        - containerPort: 80
        envFrom:
        - configMapRef:
            name: attendancepro-config
        env:
        - name: ASPNETCORE_ENVIRONMENT
          value: "Production"
        - name: ASPNETCORE_URLS
          value: "http://+:80"
        resources:
          requests:
            memory: "256Mi"
            cpu: "100m"
          limits:
            memory: "512Mi"
            cpu: "500m"
        livenessProbe:
          httpGet:
            path: /health
            port: 80
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /health
            port: 80
          initialDelaySeconds: 5
          periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: webhooks-service
  namespace: attendancepro
spec:
  selector:
    app: webhooks-service
  ports:
  - port: 80
    targetPort: 80
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: integrations-service
  namespace: attendancepro
  labels:
    app: integrations-service
    tier: backend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: integrations-service
  template:
    metadata:
      labels:
        app: integrations-service
        tier: backend
    spec:
      containers:
      - name: integrations-service
        image: attendancepro/integrations-service:latest
        ports:
        - containerPort: 80
        envFrom:
        - configMapRef:
            name: attendancepro-config
        env:
        - name: ASPNETCORE_ENVIRONMENT
          value: "Production"
        - name: ASPNETCORE_URLS
          value: "http://+:80"
        resources:
          requests:
            memory: "256Mi"
            cpu: "100m"
          limits:
            memory: "512Mi"
            cpu: "500m"
        livenessProbe:
          httpGet:
            path: /health
            port: 80
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /health
            port: 80
          initialDelaySeconds: 5
          periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: integrations-service
  namespace: attendancepro
spec:
  selector:
    app: integrations-service
  ports:
  - port: 80
    targetPort: 80
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: attendancepro
  labels:
    app: frontend
    tier: frontend
spec:
  replicas: 3
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
        tier: frontend
    spec:
      containers:
      - name: frontend
        image: attendancepro/frontend:latest
        ports:
        - containerPort: 80
        resources:
          requests:
            memory: "128Mi"
            cpu: "50m"
          limits:
            memory: "256Mi"
            cpu: "200m"
        livenessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 5
          periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: frontend-service
  namespace: attendancepro
spec:
  selector:
    app: frontend
  ports:
  - port: 80
    targetPort: 80
  type: LoadBalancer

