apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "hudur.fullname" . }}-analytics
  labels:
    {{- include "hudur.labels" . | nindent 4 }}
    app.kubernetes.io/component: analytics
spec:
  replicas: {{ .Values.analytics.replicaCount }}
  selector:
    matchLabels:
      {{- include "hudur.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: analytics
  template:
    metadata:
      labels:
        {{- include "hudur.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: analytics
    spec:
      serviceAccountName: {{ include "hudur.serviceAccountName" . }}
      containers:
      - name: analytics
        image: "{{ .Values.analytics.image.repository }}:{{ .Values.analytics.image.tag | default .Chart.AppVersion }}"
        imagePullPolicy: {{ .Values.analytics.image.pullPolicy }}
        ports:
        - name: http
          containerPort: 8080
          protocol: TCP
        - name: https
          containerPort: 8443
          protocol: TCP
        env:
        - name: ASPNETCORE_ENVIRONMENT
          value: {{ .Values.global.environment }}
        - name: ASPNETCORE_URLS
          value: "https://+:8443;http://+:8080"
        - name: ConnectionStrings__DefaultConnection
          valueFrom:
            secretKeyRef:
              name: {{ include "hudur.fullname" . }}-secrets
              key: database-connection-string
        - name: ConnectionStrings__AnalyticsConnection
          valueFrom:
            secretKeyRef:
              name: {{ include "hudur.fullname" . }}-secrets
              key: analytics-database-connection-string
        - name: Redis__ConnectionString
          valueFrom:
            secretKeyRef:
              name: {{ include "hudur.fullname" . }}-secrets
              key: redis-connection-string
        - name: AnalyticsSettings__PredictiveEnabled
          value: "{{ .Values.analytics.predictive.enabled }}"
        - name: AnalyticsSettings__MachineLearningEnabled
          value: "{{ .Values.analytics.machineLearning.enabled }}"
        - name: AnalyticsSettings__RealTimeProcessing
          value: "{{ .Values.analytics.realTime.enabled }}"
        - name: BusinessIntelligenceSettings__Enabled
          value: "{{ .Values.analytics.businessIntelligence.enabled }}"
        - name: DataRetentionSettings__Days
          value: "{{ .Values.analytics.dataRetention.days }}"
        - name: AuthenticationService__BaseUrl
          value: "http://{{ include "hudur.fullname" . }}-authentication:{{ .Values.authentication.service.port }}"
        - name: AttendanceService__BaseUrl
          value: "http://{{ include "hudur.fullname" . }}-attendance:{{ .Values.attendance.service.port }}"
        livenessProbe:
          httpGet:
            path: /health
            port: http
          initialDelaySeconds: 45
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /health/ready
            port: http
          initialDelaySeconds: 10
          periodSeconds: 5
        resources:
          {{- toYaml .Values.analytics.resources | nindent 10 }}
        volumeMounts:
        - name: certificates
          mountPath: /app/certificates
          readOnly: true
        - name: analytics-data
          mountPath: /app/data/analytics
      volumes:
      - name: certificates
        secret:
          secretName: {{ include "hudur.fullname" . }}-tls-certs
      - name: analytics-data
        persistentVolumeClaim:
          claimName: {{ include "hudur.fullname" . }}-analytics-data-pvc
      {{- with .Values.analytics.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.analytics.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.analytics.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "hudur.fullname" . }}-analytics
  labels:
    {{- include "hudur.labels" . | nindent 4 }}
    app.kubernetes.io/component: analytics
spec:
  type: {{ .Values.analytics.service.type }}
  ports:
  - port: {{ .Values.analytics.service.port }}
    targetPort: http
    protocol: TCP
    name: http
  - port: {{ .Values.analytics.service.httpsPort }}
    targetPort: https
    protocol: TCP
    name: https
  selector:
    {{- include "hudur.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: analytics
---
{{- if .Values.analytics.autoscaling.enabled }}
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: {{ include "hudur.fullname" . }}-analytics
  labels:
    {{- include "hudur.labels" . | nindent 4 }}
    app.kubernetes.io/component: analytics
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ include "hudur.fullname" . }}-analytics
  minReplicas: {{ .Values.analytics.autoscaling.minReplicas }}
  maxReplicas: {{ .Values.analytics.autoscaling.maxReplicas }}
  metrics:
  {{- if .Values.analytics.autoscaling.targetCPUUtilizationPercentage }}
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: {{ .Values.analytics.autoscaling.targetCPUUtilizationPercentage }}
  {{- end }}
  {{- if .Values.analytics.autoscaling.targetMemoryUtilizationPercentage }}
  - type: Resource
    resource:
      name: memory
      target:
        type: Utilization
        averageUtilization: {{ .Values.analytics.autoscaling.targetMemoryUtilizationPercentage }}
  {{- end }}
{{- end }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "hudur.fullname" . }}-analytics-data-pvc
  labels:
    {{- include "hudur.labels" . | nindent 4 }}
    app.kubernetes.io/component: analytics
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.analytics.storage.size }}
  {{- if .Values.analytics.storage.storageClass }}
  storageClassName: {{ .Values.analytics.storage.storageClass }}
  {{- end }}
