apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "hudur.fullname" . }}-authentication
  labels:
    {{- include "hudur.labels" . | nindent 4 }}
    app.kubernetes.io/component: authentication
spec:
  replicas: {{ .Values.authentication.replicaCount }}
  selector:
    matchLabels:
      {{- include "hudur.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: authentication
  template:
    metadata:
      labels:
        {{- include "hudur.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: authentication
    spec:
      serviceAccountName: {{ include "hudur.serviceAccountName" . }}
      containers:
      - name: authentication
        image: "{{ .Values.authentication.image.repository }}:{{ .Values.authentication.image.tag | default .Chart.AppVersion }}"
        imagePullPolicy: {{ .Values.authentication.image.pullPolicy }}
        ports:
        - name: http
          containerPort: 8080
          protocol: TCP
        - name: https
          containerPort: 8443
          protocol: TCP
        env:
        - name: ASPNETCORE_ENVIRONMENT
          value: {{ .Values.global.environment }}
        - name: ASPNETCORE_URLS
          value: "https://+:8443;http://+:8080"
        - name: ConnectionStrings__DefaultConnection
          valueFrom:
            secretKeyRef:
              name: {{ include "hudur.fullname" . }}-secrets
              key: database-connection-string
        - name: JwtSettings__SecretKey
          valueFrom:
            secretKeyRef:
              name: {{ include "hudur.fullname" . }}-secrets
              key: jwt-secret-key
        - name: JwtSettings__Issuer
          value: {{ .Values.global.domain }}
        - name: JwtSettings__Audience
          value: {{ .Values.global.domain }}
        - name: Redis__ConnectionString
          valueFrom:
            secretKeyRef:
              name: {{ include "hudur.fullname" . }}-secrets
              key: redis-connection-string
        - name: EmailSettings__SmtpHost
          value: {{ .Values.global.smtp.host }}
        - name: EmailSettings__SmtpPort
          value: "{{ .Values.global.smtp.port }}"
        - name: EmailSettings__Username
          valueFrom:
            secretKeyRef:
              name: {{ include "hudur.fullname" . }}-secrets
              key: smtp-username
        - name: EmailSettings__Password
          valueFrom:
            secretKeyRef:
              name: {{ include "hudur.fullname" . }}-secrets
              key: smtp-password
        - name: TwoFactorSettings__Enabled
          value: "{{ .Values.authentication.twoFactor.enabled }}"
        - name: BiometricSettings__Enabled
          value: "{{ .Values.authentication.biometric.enabled }}"
        livenessProbe:
          httpGet:
            path: /health
            port: http
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /health/ready
            port: http
          initialDelaySeconds: 5
          periodSeconds: 5
        resources:
          {{- toYaml .Values.authentication.resources | nindent 10 }}
        volumeMounts:
        - name: certificates
          mountPath: /app/certificates
          readOnly: true
      volumes:
      - name: certificates
        secret:
          secretName: {{ include "hudur.fullname" . }}-tls-certs
      {{- with .Values.authentication.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.authentication.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.authentication.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "hudur.fullname" . }}-authentication
  labels:
    {{- include "hudur.labels" . | nindent 4 }}
    app.kubernetes.io/component: authentication
spec:
  type: {{ .Values.authentication.service.type }}
  ports:
  - port: {{ .Values.authentication.service.port }}
    targetPort: http
    protocol: TCP
    name: http
  - port: {{ .Values.authentication.service.httpsPort }}
    targetPort: https
    protocol: TCP
    name: https
  selector:
    {{- include "hudur.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: authentication
---
{{- if .Values.authentication.autoscaling.enabled }}
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: {{ include "hudur.fullname" . }}-authentication
  labels:
    {{- include "hudur.labels" . | nindent 4 }}
    app.kubernetes.io/component: authentication
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ include "hudur.fullname" . }}-authentication
  minReplicas: {{ .Values.authentication.autoscaling.minReplicas }}
  maxReplicas: {{ .Values.authentication.autoscaling.maxReplicas }}
  metrics:
  {{- if .Values.authentication.autoscaling.targetCPUUtilizationPercentage }}
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: {{ .Values.authentication.autoscaling.targetCPUUtilizationPercentage }}
  {{- end }}
  {{- if .Values.authentication.autoscaling.targetMemoryUtilizationPercentage }}
  - type: Resource
    resource:
      name: memory
      target:
        type: Utilization
        averageUtilization: {{ .Values.authentication.autoscaling.targetMemoryUtilizationPercentage }}
  {{- end }}
{{- end }}
