apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "hudur.fullname" . }}-facerecognition
  labels:
    {{- include "hudur.labels" . | nindent 4 }}
    app.kubernetes.io/component: facerecognition
spec:
  replicas: {{ .Values.faceRecognition.replicaCount }}
  selector:
    matchLabels:
      {{- include "hudur.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: facerecognition
  template:
    metadata:
      labels:
        {{- include "hudur.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: facerecognition
    spec:
      serviceAccountName: {{ include "hudur.serviceAccountName" . }}
      containers:
      - name: facerecognition
        image: "{{ .Values.faceRecognition.image.repository }}:{{ .Values.faceRecognition.image.tag | default .Chart.AppVersion }}"
        imagePullPolicy: {{ .Values.faceRecognition.image.pullPolicy }}
        ports:
        - name: http
          containerPort: 8080
          protocol: TCP
        - name: https
          containerPort: 8443
          protocol: TCP
        env:
        - name: ASPNETCORE_ENVIRONMENT
          value: {{ .Values.global.environment }}
        - name: ASPNETCORE_URLS
          value: "https://+:8443;http://+:8080"
        - name: ConnectionStrings__DefaultConnection
          valueFrom:
            secretKeyRef:
              name: {{ include "hudur.fullname" . }}-secrets
              key: database-connection-string
        - name: Redis__ConnectionString
          valueFrom:
            secretKeyRef:
              name: {{ include "hudur.fullname" . }}-secrets
              key: redis-connection-string
        - name: FaceRecognitionSettings__Mode
          value: {{ .Values.faceRecognition.mode }}
        - name: FaceRecognitionSettings__CloudProvider
          value: {{ .Values.faceRecognition.cloudProvider }}
        - name: FaceRecognitionSettings__OnDeviceEnabled
          value: "{{ .Values.faceRecognition.onDevice.enabled }}"
        - name: FaceRecognitionSettings__PrivacyMode
          value: "{{ .Values.faceRecognition.privacy.enabled }}"
        - name: BiometricSettings__EncryptionEnabled
          value: "{{ .Values.faceRecognition.encryption.enabled }}"
        - name: StorageSettings__BlobConnectionString
          valueFrom:
            secretKeyRef:
              name: {{ include "hudur.fullname" . }}-secrets
              key: blob-storage-connection-string
        - name: AuthenticationService__BaseUrl
          value: "http://{{ include "hudur.fullname" . }}-authentication:{{ .Values.authentication.service.port }}"
        livenessProbe:
          httpGet:
            path: /health
            port: http
          initialDelaySeconds: 45
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /health/ready
            port: http
          initialDelaySeconds: 10
          periodSeconds: 5
        resources:
          {{- toYaml .Values.faceRecognition.resources | nindent 10 }}
        volumeMounts:
        - name: certificates
          mountPath: /app/certificates
          readOnly: true
        - name: face-templates
          mountPath: /app/data/templates
      volumes:
      - name: certificates
        secret:
          secretName: {{ include "hudur.fullname" . }}-tls-certs
      - name: face-templates
        persistentVolumeClaim:
          claimName: {{ include "hudur.fullname" . }}-face-templates-pvc
      {{- with .Values.faceRecognition.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.faceRecognition.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.faceRecognition.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "hudur.fullname" . }}-facerecognition
  labels:
    {{- include "hudur.labels" . | nindent 4 }}
    app.kubernetes.io/component: facerecognition
spec:
  type: {{ .Values.faceRecognition.service.type }}
  ports:
  - port: {{ .Values.faceRecognition.service.port }}
    targetPort: http
    protocol: TCP
    name: http
  - port: {{ .Values.faceRecognition.service.httpsPort }}
    targetPort: https
    protocol: TCP
    name: https
  selector:
    {{- include "hudur.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: facerecognition
---
{{- if .Values.faceRecognition.autoscaling.enabled }}
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: {{ include "hudur.fullname" . }}-facerecognition
  labels:
    {{- include "hudur.labels" . | nindent 4 }}
    app.kubernetes.io/component: facerecognition
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ include "hudur.fullname" . }}-facerecognition
  minReplicas: {{ .Values.faceRecognition.autoscaling.minReplicas }}
  maxReplicas: {{ .Values.faceRecognition.autoscaling.maxReplicas }}
  metrics:
  {{- if .Values.faceRecognition.autoscaling.targetCPUUtilizationPercentage }}
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: {{ .Values.faceRecognition.autoscaling.targetCPUUtilizationPercentage }}
  {{- end }}
  {{- if .Values.faceRecognition.autoscaling.targetMemoryUtilizationPercentage }}
  - type: Resource
    resource:
      name: memory
      target:
        type: Utilization
        averageUtilization: {{ .Values.faceRecognition.autoscaling.targetMemoryUtilizationPercentage }}
  {{- end }}
{{- end }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "hudur.fullname" . }}-face-templates-pvc
  labels:
    {{- include "hudur.labels" . | nindent 4 }}
    app.kubernetes.io/component: facerecognition
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.faceRecognition.storage.size }}
  {{- if .Values.faceRecognition.storage.storageClass }}
  storageClassName: {{ .Values.faceRecognition.storage.storageClass }}
  {{- end }}
