apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "hudur.fullname" . }}-notifications
  labels:
    {{- include "hudur.labels" . | nindent 4 }}
    app.kubernetes.io/component: notifications
spec:
  replicas: {{ .Values.notifications.replicaCount }}
  selector:
    matchLabels:
      {{- include "hudur.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: notifications
  template:
    metadata:
      labels:
        {{- include "hudur.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: notifications
    spec:
      serviceAccountName: {{ include "hudur.serviceAccountName" . }}
      containers:
      - name: notifications
        image: "{{ .Values.notifications.image.repository }}:{{ .Values.notifications.image.tag | default .Chart.AppVersion }}"
        imagePullPolicy: {{ .Values.notifications.image.pullPolicy }}
        ports:
        - name: http
          containerPort: 8080
          protocol: TCP
        - name: https
          containerPort: 8443
          protocol: TCP
        env:
        - name: ASPNETCORE_ENVIRONMENT
          value: {{ .Values.global.environment }}
        - name: ASPNETCORE_URLS
          value: "https://+:8443;http://+:8080"
        - name: ConnectionStrings__DefaultConnection
          valueFrom:
            secretKeyRef:
              name: {{ include "hudur.fullname" . }}-secrets
              key: database-connection-string
        - name: Redis__ConnectionString
          valueFrom:
            secretKeyRef:
              name: {{ include "hudur.fullname" . }}-secrets
              key: redis-connection-string
        - name: EmailSettings__SmtpHost
          value: {{ .Values.global.smtp.host }}
        - name: EmailSettings__SmtpPort
          value: "{{ .Values.global.smtp.port }}"
        - name: EmailSettings__Username
          valueFrom:
            secretKeyRef:
              name: {{ include "hudur.fullname" . }}-secrets
              key: smtp-username
        - name: EmailSettings__Password
          valueFrom:
            secretKeyRef:
              name: {{ include "hudur.fullname" . }}-secrets
              key: smtp-password
        - name: SmsSettings__Provider
          value: {{ .Values.notifications.sms.provider }}
        - name: SmsSettings__ApiKey
          valueFrom:
            secretKeyRef:
              name: {{ include "hudur.fullname" . }}-secrets
              key: sms-api-key
        - name: PushNotificationSettings__Enabled
          value: "{{ .Values.notifications.push.enabled }}"
        - name: SlackSettings__WebhookUrl
          valueFrom:
            secretKeyRef:
              name: {{ include "hudur.fullname" . }}-secrets
              key: slack-webhook-url
        - name: TeamsSettings__WebhookUrl
          valueFrom:
            secretKeyRef:
              name: {{ include "hudur.fullname" . }}-secrets
              key: teams-webhook-url
        livenessProbe:
          httpGet:
            path: /health
            port: http
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /health/ready
            port: http
          initialDelaySeconds: 5
          periodSeconds: 5
        resources:
          {{- toYaml .Values.notifications.resources | nindent 10 }}
        volumeMounts:
        - name: certificates
          mountPath: /app/certificates
          readOnly: true
      volumes:
      - name: certificates
        secret:
          secretName: {{ include "hudur.fullname" . }}-tls-certs
      {{- with .Values.notifications.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.notifications.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.notifications.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "hudur.fullname" . }}-notifications
  labels:
    {{- include "hudur.labels" . | nindent 4 }}
    app.kubernetes.io/component: notifications
spec:
  type: {{ .Values.notifications.service.type }}
  ports:
  - port: {{ .Values.notifications.service.port }}
    targetPort: http
    protocol: TCP
    name: http
  - port: {{ .Values.notifications.service.httpsPort }}
    targetPort: https
    protocol: TCP
    name: https
  selector:
    {{- include "hudur.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: notifications
---
{{- if .Values.notifications.autoscaling.enabled }}
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: {{ include "hudur.fullname" . }}-notifications
  labels:
    {{- include "hudur.labels" . | nindent 4 }}
    app.kubernetes.io/component: notifications
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ include "hudur.fullname" . }}-notifications
  minReplicas: {{ .Values.notifications.autoscaling.minReplicas }}
  maxReplicas: {{ .Values.notifications.autoscaling.maxReplicas }}
  metrics:
  {{- if .Values.notifications.autoscaling.targetCPUUtilizationPercentage }}
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: {{ .Values.notifications.autoscaling.targetCPUUtilizationPercentage }}
  {{- end }}
  {{- if .Values.notifications.autoscaling.targetMemoryUtilizationPercentage }}
  - type: Resource
    resource:
      name: memory
      target:
        type: Utilization
        averageUtilization: {{ .Values.notifications.autoscaling.targetMemoryUtilizationPercentage }}
  {{- end }}
{{- end }}
