{{- if .Values.secrets.create }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "hudur.fullname" . }}-secrets
  labels:
    {{- include "hudur.labels" . | nindent 4 }}
type: Opaque
data:
  database-connection-string: {{ include "hudur.databaseConnectionString" . | b64enc }}
  redis-connection-string: {{ include "hudur.redisConnectionString" . | b64enc }}
  jwt-secret-key: {{ include "hudur.jwtSecretKey" . }}
  encryption-key: {{ include "hudur.encryptionKey" . }}
  smtp-username: {{ .Values.global.smtp.username | default "admin@hudur.sa" | b64enc }}
  smtp-password: {{ .Values.global.smtp.password | default "${SMTP_PASSWORD}" | b64enc }}
  sms-api-key: {{ .Values.notifications.sms.apiKey | default "${SMS_API_KEY}" | b64enc }}
  slack-webhook-url: {{ .Values.notifications.slack.webhookUrl | default "" | b64enc }}
  teams-webhook-url: {{ .Values.notifications.teams.webhookUrl | default "" | b64enc }}
  blob-storage-connection-string: {{ .Values.global.storage.connectionString | default "${STORAGE_CONNECTION_STRING}" | b64enc }}
  analytics-database-connection-string: {{ .Values.analytics.database.connectionString | default (include "hudur.databaseConnectionString" .) | b64enc }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "hudur.fullname" . }}-tls-certs
  labels:
    {{- include "hudur.labels" . | nindent 4 }}
type: kubernetes.io/tls
data:
  {{- include "hudur.generateCert" . | nindent 2 }}
{{- end }}
